export const SUCCESS_CODE = 200;
export const typeProvinces = {
  ALL_PROVINCES_REQUEST: "ALL_PROVINCES_REQUEST",
  ADD_PROVINCES_REQUEST: "ADD_PROVINCES_REQUEST",
  EDIT_PROVINCES_REQUEST: "EDIT_PROVINCES_REQUEST",
  DELETE_PROVINCE_REQUEST: "DELETE_PROVINCE_REQUEST",
  SEARCH_PROVINCES_REQUEST: "SEARCH_PROVINCES_REQUEST",
  GET_DISTRICT_BY_PROVINCE_REQUEST: "GET_DISTRICT_BY_PROVINCE_REQUEST",
};
export const typeDistricts = {
  GET_ALL_DISTRICT_SAGA_REQUEST: "GET_ALL_DISTRICT_SAGA_REQUEST",
  ADD_DISTRICT_REQUEST: "ADD_DISTRICT_REQUEST",
  UPDATE_DISTRICT_REQUEST: "UPDATE_DISTRICT_REQUEST",
  DELETE_DISTRICT_REQUEST: "DELETE_DISTRICT_REQUEST",
  SEARCH_DISTRICT_REQUEST: "SEARCH_DISTRICT_REQUEST",
};
export const typeWards = {
  GET_ALL_WARD_REQUEST: "GET_ALL_WARD_REQUEST",
  ADD_NEW_WARD_REQUEST: "ADD_NEW_WARD_REQUEST",
  UPDATE_WARD_REQUEST: "UPDATE_WARD_REQUEST",
  DELETE_WARD_WITH_ID: "DELETE_WARD_WITH_ID",
  SEARCH_WARD_REQUEST: "SEARCH_WARD_REQUEST",
};
export const typeEmployee = {
  GET_ALL_EMPLOYEE_REQUEST: "GET_ALL_EMPLOYEE_REQUEST",
  ADD_EMPLOYEE_REQUEST: "ADD_EMPLOYEE_REQUEST",
  UPDATE_EMPLOYEE_REQUEST: "UPDATE_EMPLOYEE_REQUEST",
  DELETE_EMPLOYEE_REQUEST: "DELETE_EMPLOYEE_REQUEST",
  SEARCH_EMPLOYEE_REQUEST: "SEARCH_EMPLOYEE_REQUEST",
};
